[tool.poetry]
name = "aw-server"
version = "0.1.0"
description = ""
authors = ["Your Name <your.email@example.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "aw_server"}]

[tool.poetry.dependencies]
python = "^3.9"
aw-core = {path = "../aw-core", develop = true}
aw-datastore = {path = "../aw_datastore", develop = true}
firebase-admin = "^6.2.0"
bleach = "^6.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
