# NOTE: To use this workflow, you must add a GitHub secret named FIRESTORE_PROJECT_ID
#       with the Firebase Project ID for your test project.
name: Firebase Security Rules Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run_rules_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI and functions dependencies
        run: |
          npm install -g firebase-tools
          npm install --prefix functions

      - name: Start Firebase Emulators and Run Tests
        run: |
          firebase emulators:exec --project ${{ secrets.FIREBASE_PROJECT_ID }} --only firestore "npm --prefix functions test functions/test/security/firestore.test.ts"
        env:
          FIRESTORE_EMULATOR_HOST: localhost:8080

  security_scan_python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Poetry
        run: pip install poetry

      - name: Install Python dependencies
        run: poetry install
        working-directory: aw-server

      - name: Run Bandit Security Scan
        run: poetry run bandit -r aw_server/ -ll -f json -o bandit-report.json
        working-directory: aw-server
      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: aw-server/bandit-report.json

      - name: Generate requirements.txt for Safety
        run: poetry export -f requirements.txt --output requirements.txt --without-hashes
        working-directory: aw-server

      - name: Run Safety Dependency Scan
        run: poetry run safety check -r requirements.txt --full-report -o safety-report.json
        working-directory: aw-server
      - name: Upload Safety Report
        uses: actions/upload-artifact@v4
        with:
          name: safety-report
          path: aw-server/safety-report.json

  security_scan_nodejs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node.js dependencies
        run: npm install
        working-directory: aw-server/aw-webui

      - name: Run npm audit
        run: npm audit --json > npm-audit-report.json || true
        working-directory: aw-server/aw-webui
      - name: Upload npm Audit Report
        uses: actions/upload-artifact@v4
        with:
          name: npm-audit-report
          path: aw-server/aw-webui/npm-audit-report.json
